### ISSUE TITLE
Perlin noise value range isn't actually 0 to 1

### ISSUE THREAD

**Issue by Barteks2x** [SpongePowered/noise#18]
Well, **technically** it is. But technically it's also between -infinity and +infinity. After testing with 64 million samples (not random, some predefined area) I got min=0.30759661550127604, max=0.692403384498724. It seems safe to say that the actual value range that happens in practice is 0.3 to 0.7. When eriting terrain generator using it with the assumption that the value range will be 0 to 1, the terrain will never reach values even halfway through to the intended max height and depth.

I also did an experiment replacing the `RANDOM_VECTORS` array (I currently use that "hack" in my code) with the values Minecarft uses internally - which is all possibilities with 2 coordinates being +/-1 and one coordinate being zero - prescaled down by 0.5 to make halve the value range so that after adding 0.5 - the resulting range is 0-1. After testing with the same 64 million samples, I got the **exact** value range of 0 to 1. Not 0.00000001 to 0.999999999, exactly 0.0 to 1.0. There are actually 12 such vectors, so I choose them randomly to fill the whole array.

And some images (this is the frequency I used for sampling, just 8k by 8k image, pixel color intensity is `clamp(floor(value * 256), 0, 1)`:
Current values:
![bad](https://cloud.githubusercontent.com/assets/1349112/26494393/c6f9d43a-421e-11e7-876b-d2f2a8bd6ff0.png)
"fixed" values:
![good](https://cloud.githubusercontent.com/assets/1349112/26494394/c6fbc254-421e-11e7-8d29-cb43b1d346fa.png)

Unfortunately, fixing this will break compatibility with existing code, so maybe another option would be updating documentation to say that?

**Comment by Barteks2x** [comment]
I forgot... I should probably also test it with non-zero `z` coordinate.

**Comment by DDoS** [comment]
That's expected because the values 0 and 1 have very low probabilities of occurring. Also this is only for a single octave, you should be using more to increase the range.

**Comment by Barteks2x** [comment]
the real perlin noise should have full value range. And it's not just rare here, it's impossible to achive. And I think I could probably could actually prove that you can't get value above 0.75 with this implementation.

Perlin class has getMaxValue which returns the "true" max value **assuming ssingle octave return s values between 0 and 1**.

All other noise generator implementations return values between 0 and 1 or -1 and 1 for a single octave.

**Comment by Barteks2x** [comment]
I can run through all possibilities of choosing 8 random vectors for the corners, and for each of such combinations scan find the max value

**Comment by DDoS** [comment]
If you can prove that 0 and 1 are impossible values, then it's a bug that must be fixed.

**Comment by me4502** [comment]
Out of curiosity, what code did you use to generate those images?

**Comment by Barteks2x** [comment]
I no longer have the exact code, but it should be reasonably simple to reimplement it. I didn't do exhaustive search for min and max values yes because I have a known working workaround.

**Comment by me4502** [comment]
Hmm, I ask because I’m having trouble getting it to give me different results. Every time I run the function it provides the same result, even with different values. My thought was that as I’m doing it 2D with 0 as the z value that’s the cause.

**Comment by Barteks2x** [comment]
What is the frequency you are using? Are you using the Perlin class or directly the Noise class?
Perlin noise will always have the same values at integer coordinates.

**Comment by me4502** [comment]
So the issue is I was using a frequency of 1 with integer coordinates. However, now I'm encountering the issue mentioned in this issue.

I appear to be getting a value between 0.9 and 1.4

**Comment by Barteks2x** [comment]
Then you are using default amount of octaves most likely, which isn't 1. With one octave you would get something between 0.3 and 0.7.

**Comment by Barteks2x** [comment]
I mostly forgot about the issue because I had a hack in my code to make it work, but here is Ken Perlin's paper that actually says your code is wrong: http://mrl.nyu.edu/~perlin/paper445.pdf

From the paper:

> The key to removing directional bias in the gradients is to skew
the set of gradient directions away from the coordinate axes and
long diagonals. (...) The corrected version
replaces G with the 12 vectors defined by the directions from the
center of a cube to its edges:
(1,1,0),(-1,1,0),(1,-1,0),(-1,-1,0),
(1,0,1),(-1,0,1),(1,0,-1),(-1,0,-1),
(0,1,1),(0,-1,1),(0,1,-1),(0,-1,-1)
Gradients from this set are chosen by using the result of P,
modulo 12. This set of gradient directions was chosen for two
reasons: (i) it avoids the main axis and long diagonal directions,
thereby avoiding the possibility of axis-aligned clumping, and (ii)
it allows the eight inner products to be effected without requiring
any multiplies, thereby removing 24 multiplies from the
computation.
To avoid the cost of dividing by 12, we pad to 16 gradient
directions, adding an extra (1,1,0),(-1,1,0),(0,-1,1) and (0,-1,-1).
These form a regular tetrahedron, so adding them redundantly
introduces no visual bias in the texture. The final result has the
same non-directional appearance as the original distribution but
less clumping, as can be seen in Figure 2b.

**Comment by mattes3** [comment]
BTW, [this article here](http://digitalfreepen.com/2017/06/20/range-perlin-noise.html) says that the range is [−sqrt(N/4),sqrt(N/4)] where N is the dimension of the noise function. So, for 2D Perlin noise, you get a range from -.707 to +.707 and for 3D Perlin noise, you get a range from -.866 to +.866

What do you think?

**Comment by Barteks2x** [comment]
I did some math on it and what I got agrees with the above.

I will try to explain why the current approach produces the results it does, and explain it here:

---------------------------

![image](https://user-images.githubusercontent.com/1349112/61999795-3a079000-b0c9-11e9-9069-11165ed6c553.png)

This image shows a 2d version of a scenario with maximum possible value, it's similar in 3d, with all the gradient vectors pointing towards the center. Intuitively, the maximum value is going to be right at the center, and the value will be an exact average of contributions from all corners. Since the values from all corners is going to be the same value, the result is going to be the same as the value from just one of them.

This library creates the value as follows (excluding the changes needed to make it 0-1, assume -1 to 1 target here): `(xvGradient * xvPoint) + (yvGradient * yvPoint) + (zvGradient * zvPoint)`.
`xvPoint = yvPoint= zvPoint = 0.5` in this case. And also `xvGradient = yvGradient = zvGradient` such that `sqrt(x*x + y*y + z*z) = 1`, which makes that value be `sqrt(3)/3`. Substituting the values we get:
`0.5*sqrt(3)/3 + 0.5*sqrt(3)/3 + 0.5*sqrt(3)/3 = 0.5*sqrt(3) = 0.8660254037844386`. Which is the value mentioned in comment above.
 Now rescaling it to be between 0 and 1: `(0.8660254037844386 + 1) / 2 = 0.9330127018922193`

Before this PR: https://github.com/SpongePowered/noise/pull/13/files this value would then STILL be divided by `1.728003` (which is sqrt(3), and then again by 2 to rescale to 0-1, this PR just integrated it into the gradient vectors as optimization). So dividing that by sqrt(3) we get exactly 0.5. And rescaling to 0-1 the total max value possible turns out to be 0.75. Not too far off from the `0.692403384498724` I got during my initial testing, which is very likely a result of never actually being able to get the lucky arrangement of gradient vectors that results in theoretical maximum.

--------------------

I also did some tests with using the values I mentioned previously, and there are still a few things I don't understand. I tested all the possible `12^8 = 429981696` possibilities of gradients in that form being used, and the theoretical maximum I got from there is `5/3 = 1.6666666...`, which doesn't agree with my previously done tests at all and I can't figure out why (and excluding one dimension just changed lowered it to about 1.2).

-------------------

In any case, I don't think it would be ok to change it now as it would change any world generator that relies on it.

**Comment by Cybermaxke** [comment]
It could be the time to fix it now, since the namespace already changed. But there should be an option for backwards compatibility.

**Comment by Barteks2x** [comment]
Would backwards compatibility be the default, or would it need to be enabled? I can try to write a PR for that.

**Comment by Zidane** [comment]
Closed with the merge of #20 

Thanks to everyone who commented on this.
