### ISSUE TITLE
Perlin noise value is the same for every point

### ISSUE THREAD

**Issue by realkarmakun** [SpongePowered/noise#27]
Here is snippet of noise value examples from 10x10x10 cuboid:
```
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, -4, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, -3, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, -2, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, -1, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, 0, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, 1, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, 2, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, 3, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, 4, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, 5, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, 6, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, 7, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, 8, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, 9, 0] is 1.6301681263765515
[16:05:17] [Server thread/INFO] [ens3]: Value for [8, -10, 1] is 1.6301681263765515
```

Code I use for initializing Perlin noise module:
```java
public class ProceduralGenerator {
    private final Module heightGenerator;

    public ProceduralGenerator() {
        var perlinModule = new Perlin();
        perlinModule.setPersistence(0.714);
        perlinModule.setOctaveCount(8);
        heightGenerator = perlinModule;

    }

    public double applyCoordinates(Vector3d position) {
        return heightGenerator.getValue(position.x(), position.y(), position.z());
    }
}
```

As pointed out by `Diggy` in SpongePowered Discord (https://discord.com/channels/142425412096491520/142425521391665153/893802421703278622) issue also seems to affect billow and ridged multi.

**Comment by GuusLieben** [comment]
For easy reference; Billow, RidgedMutli, and Perlin are the only three modules which show this behavior, and are also the only three using [`Noise.gradientCoherentNoise3D`](https://github.com/SpongePowered/noise/blob/d910537d4d6df056e8177989ac39b50d9a7da5c3/src/main/java/org/spongepowered/noise/Noise.java#L147).  See [`Billow#L275`](https://github.com/SpongePowered/noise/blob/d910537d4d6df056e8177989ac39b50d9a7da5c3/src/main/java/org/spongepowered/noise/module/source/Billow.java#L275), [`Perlin#L377`](https://github.com/SpongePowered/noise/blob/d910537d4d6df056e8177989ac39b50d9a7da5c3/src/main/java/org/spongepowered/noise/module/source/Perlin.java#L377), and [`RidgedMulti#L333`](https://github.com/SpongePowered/noise/blob/d910537d4d6df056e8177989ac39b50d9a7da5c3/src/main/java/org/spongepowered/noise/module/source/RidgedMulti.java#L333).  

I used the following snippet to test the behavior of each module:
```java
Module[] modules = {new Billow(), new Checkerboard(), new Cylinders(), new Perlin(), new RidgedMulti(), new RidgedMultiSimplex(), new Simplex(), new Spheres(), new Voronoi() };
for (Module module : modules) {
    System.out.println("Next module: " + module.getClass().getSimpleName());
    int size = 100;
    for (int i = 0; i < size; i++) {
        for (int j = 0; j < size; j++) {
            System.out.println(module.getValue(i, j, i));
        }
    }
}
```

The result of [`Noise.gradientCoherentNoise3D`](https://github.com/SpongePowered/noise/blob/d910537d4d6df056e8177989ac39b50d9a7da5c3/src/main/java/org/spongepowered/noise/Noise.java#L147) seems to always be `0.5`, I suspect this is the cause for the constant output values.

**Comment by Lignium** [comment]
I think you need to decrease frequency of the noise.
`Perlin#setFrequency(...)`

**Comment by realkarmakun** [comment]
> 
> 
> I think you need to decrease frequency of the noise. `Perlin#setFrequency(...)`

Lowering frequency helped. Values now change. Is there any way to choose a best value for a set? For example I have 6000 points, is there any way to know what frequency would work the best without trying over and over again?

**Comment by Lignium** [comment]
It depends on task, where you apply the noise. You can assume that this is scale of noise, by default it is excessively increased. In any case, you will have to select value, I would say, as in binary search.

**Comment by DDoS** [comment]
This is happening because you're sampling on integer coordinates. It's a property of Perlin noise.

The default frequency value is 1, so it doesn't change the sampling values. If you change it something else it should result in non-integer sampling value inside the algorithm, which will give a random-like output.

Pick a frequency that is the inverse of the size of the largest feature you want in your output. Make sure to set the octave count such that the highest octave frequency matches the size of your smallest feature. Each successive octave doubles the frequency of the previous one.

Hopes this helps.
